// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/MuxiKeStack/be-comment/grpc"
	"github.com/MuxiKeStack/be-comment/ioc"
	"github.com/MuxiKeStack/be-comment/pkg/grpcx"
	"github.com/MuxiKeStack/be-comment/repository"
	"github.com/MuxiKeStack/be-comment/repository/cache"
	"github.com/MuxiKeStack/be-comment/repository/dao"
	"github.com/MuxiKeStack/be-comment/service"
)

// Injectors from wire.go:

func InitGRPCServer() grpcx.Server {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	commentDAO := dao.NewCommentDAO(db)
	cmdable := ioc.InitRedis()
	commentCache := cache.NewRedisCommentCache(cmdable)
	commentRepository := repository.NewCachedCommentRepo(commentDAO, commentCache, logger)
	client := ioc.InitKafka()
	producer := ioc.InitProducer(client)
	clientv3Client := ioc.InitEtcdClient()
	evaluationServiceClient := ioc.InitEvaluationClient(clientv3Client)
	answerServiceClient := ioc.InitAnswerClient(clientv3Client)
	commentService := service.NewCommentService(commentRepository, producer, evaluationServiceClient, answerServiceClient, logger)
	commentServiceServer := grpc.NewCommentServiceServer(commentService)
	server := ioc.InitGRPCxKratosServer(commentServiceServer, clientv3Client, logger)
	return server
}
