---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xishan.
--- DateTime: 2024/5/1 01:39
---

local key = KEYS[1]
local delta = tonumber(ARGV[1])
local exists = redis.call("EXISTS", key)
if exists == 1 then
    redis.call("INCRBY", key, delta)
    return 1
else
    return 0
end