mysql:
  dsn: "root:root@tcp(localhost:3306)/kstack"

redis:
  addr: "localhost:6379"

etcd:
  endpoints:
    - "localhost:12379"

grpc:
  server:
    name: "comment"
    weight: 100
    addr: ":8097"
    etcdTTL: 60
  client:
    answer:
      endpoint: "discovery:///answer"
    evaluation:
      endpoint: "discovery:///evaluation"

kafka:
  addrs:
    - "localhost:9094"